LANGUAGE_EN = 'en'
LANGUAGE_RU = 'ru'
LANGUAGE_KK = 'kk'

LANGUAGE_CHOICES = [
    (LANGUAGE_EN, 'English'),
    (LANGUAGE_RU, 'Russian'),
    (LANGUAGE_KK, 'Kazakh'),
]

SUPPORTED_LANGUAGES = [LANGUAGE_EN, LANGUAGE_RU, LANGUAGE_KK]
